version: '3.8'

services:
  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: interview_tracker_frontend
    environment:
      # Environment configuration
      REACT_APP_ENV: ${REACT_APP_ENV:-production}
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8000}
      REACT_APP_APP_NAME: ${REACT_APP_APP_NAME:-Interview Position Tracker}
      REACT_APP_VERSION: ${REACT_APP_VERSION:-1.0.0}
      REACT_APP_DEBUG: ${REACT_APP_DEBUG:-false}
      REACT_APP_ENABLE_DEVTOOLS: ${REACT_APP_ENABLE_DEVTOOLS:-false}
      REACT_APP_LOG_LEVEL: ${REACT_APP_LOG_LEVEL:-error}
      GENERATE_SOURCEMAP: ${GENERATE_SOURCEMAP:-false}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - interview_tracker_network
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

networks:
  interview_tracker_network:
    external: true
