version: '3.8'

# Production Docker Compose configuration for Frontend
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  frontend:
    environment:
      REACT_APP_ENV: production
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_APP_NAME: ${REACT_APP_APP_NAME:-Interview Position Tracker}
      REACT_APP_VERSION: ${REACT_APP_VERSION:-1.0.0}
      REACT_APP_DEBUG: "false"
      REACT_APP_ENABLE_DEVTOOLS: "false"
      REACT_APP_LOG_LEVEL: error
      GENERATE_SOURCEMAP: "false"
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  # Nginx reverse proxy for frontend
  frontend-nginx:
    image: nginx:alpine
    container_name: interview_tracker_frontend_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-frontend.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    restart: always
    networks:
      - interview_tracker_network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback

networks:
  interview_tracker_network:
    external: true
