# Render deployment configuration for backend API
# This file should be placed in the root of your backend repository

# Use Docker deployment
dockerfilePath: ./Dockerfile

# Build command (for Docker)
buildCommand: |
  docker build -t job-search-tracker-api .
  # Run database migrations after container is built
  docker run --rm -e DATABASE_URL=$DATABASE_URL job-search-tracker-api alembic upgrade head

# Start command (Docker will use CMD from Dockerfile)
startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips "*"

# Environment variables (set these in Render dashboard)
# DATABASE_URL=postgresql://postgres:[PASSWORD]@[PROJECT_REF].supabase.co:5432/postgres
# SECRET_KEY=[GENERATE_A_SECURE_SECRET_KEY]
# BACKEND_CORS_ORIGINS=["https://your-frontend-domain.onrender.com"]
# ENVIRONMENT=production
# DEBUG=false
# LOG_LEVEL=INFO

# Health check
healthCheckPath: /health

# Auto-deploy from main branch
autoDeploy: true
