apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-tracker-api
  namespace: interview-tracker
  labels:
    app: interview-position-tracker
    component: api
    portWorkload: interview-tracker-api
    service: job-search-tracker-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: interview-position-tracker
      component: api
  template:
    metadata:
      labels:
        app: interview-position-tracker
        component: api
    spec:
      containers:
      - name: api
        image: haim9798/job-search-tracker-api:latest  # Replace with your actual DockerHub image
        ports:
        - containerPort: 8000
        env:
        # Configuration from ConfigMap
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: ENVIRONMENT
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: DEBUG
        - name: TESTING
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: TESTING
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: LOG_LEVEL
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        - name: ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: ALGORITHM
        - name: HEALTH_CHECK_ENABLED
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: HEALTH_CHECK_ENABLED
        - name: BACKEND_CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: BACKEND_CORS_ORIGINS
        
        # Secrets
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: interview-tracker-secrets
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: interview-tracker-secrets
              key: DATABASE_URL
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Startup probe for slow-starting containers
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        
        # Resource limits and requests
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false  # Set to true if your app supports it
          capabilities:
            drop:
            - ALL
      
      # Pod security context
      securityContext:
        fsGroup: 1000
      
      # Restart policy
      restartPolicy: Always