apiVersion: batch/v1
kind: Job
metadata:
  name: interview-tracker-migration
  namespace: interview-tracker
  labels:
    app: interview-position-tracker
    component: migration
spec:
  template:
    metadata:
      labels:
        app: interview-position-tracker
        component: migration
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migration
        image: interview-tracker-api:latest  # Same image as API
        command: ["alembic", "upgrade", "head"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: interview-tracker-secrets
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000
  backoffLimit: 3
  activeDeadlineSeconds: 300  # 5 minutes timeout