apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: interview-tracker
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: python:3.11-slim
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: interview-tracker-secrets
              key: secret-key
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        - name: ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: ALGORITHM
        - name: ENVIRONMENT
          value: "development"
        - name: DEBUG
          value: "true"
        - name: TESTING
          value: "false"
        - name: BACKEND_CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: BACKEND_CORS_ORIGINS
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: LOG_LEVEL
        - name: HEALTH_CHECK_ENABLED
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: HEALTH_CHECK_ENABLED
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: interview-tracker-config
              key: REDIS_URL
        command: ["/bin/bash"]
        args: ["-c", "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
        workingDir: /app
        volumeMounts:
        - name: app-code
          mountPath: /app
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: app-code
        hostPath:
          path: /home/haim/github/job-search-tracker-api
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: interview-tracker
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
