apiVersion: v1
kind: ConfigMap
metadata:
  name: interview-tracker-config
  namespace: interview-tracker
data:
  # Application Configuration for Minikube
  REACT_APP_ENV: "development"
  REACT_APP_API_URL: "http://api.interview-tracker.local"
  REACT_APP_APP_NAME: "Interview Position Tracker"
  REACT_APP_VERSION: "1.0.0"
  REACT_APP_DEBUG: "true"
  REACT_APP_ENABLE_DEVTOOLS: "true"
  REACT_APP_LOG_LEVEL: "debug"
  GENERATE_SOURCEMAP: "true"
  
  # Database Configuration
  DATABASE_URL: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/interview_tracker"
  
  # Security Configuration
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  ALGORITHM: "HS256"
  
  # CORS Configuration
  BACKEND_CORS_ORIGINS: '["http://interview-tracker.local", "http://localhost:3000"]'
  
  # Logging Configuration
  LOG_LEVEL: "DEBUG"
  
  # Health Check Configuration
  HEALTH_CHECK_ENABLED: "true"
  
  # Performance Configuration
  WORKERS: "2"
  MAX_CONNECTIONS: "50"
  TIMEOUT: "30"
  
  # Cache Configuration
  REDIS_URL: "redis://redis:6379"
  CACHE_TTL: "3600"
  
  # Monitoring Configuration
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  
  # Feature Flags
  ENABLE_REGISTRATION: "true"
  ENABLE_EMAIL_NOTIFICATIONS: "false"
  ENABLE_ANALYTICS: "false"
  ENABLE_ERROR_TRACKING: "false"
