apiVersion: v1
kind: Secret
metadata:
  name: interview-tracker-secrets
  namespace: interview-tracker
  labels:
    app: interview-position-tracker
type: Opaque
data:
  # Base64 encoded secrets
  # To encode: echo -n "your-secret" | base64
  SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # your-super-secret-key-change-in-production
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzcWwtc2VydmljZTo1NDMyL2ludGVydmlld190cmFja2Vy  # postgresql://postgres:postgres@postgresql-service:5432/interview_tracker