name: Quick Docker Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (default: latest)'
        required: false
        default: 'latest'
        type: string

env:
  DOCKER_IMAGE: haim9798/job-search-tracker-api
  VERSION: ${{ github.event.inputs.version || 'latest' }}

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
          ${{ env.DOCKER_IMAGE }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Success
      run: |
        echo "✅ Successfully built and pushed:"
        echo "   ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}"
        echo "   ${{ env.DOCKER_IMAGE }}:latest"
        echo ""
        echo "Pull with:"
        echo "   docker pull ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}"
